'use strict';
var Alexa = require('alexa-sdk');

var APP_ID = "amzn1.ask.skill.63c133e7-9c45-4668-b082-54fa055e8501";
var SKILL_NAME = "Historic Peoria, Illinois Places";
var GET_FACT_MESSAGE = "Here's a historic Peoria place: ";
var HELP_MESSAGE = "You can ask me for a historic place in Peoria, IL, or, you can say exit... What can I help you with?";
var HELP_REPROMPT = "What can I help you with?";
var STOP_MESSAGE = "Goodbye!";
var HISTORIC_PLACES = [
    "The Central National Bank Building is a ten-story building located at 103 Southwest Adams Street in downtown Peoria, Illinois. It was designed by Daniel Burnham in 1913. Burnham himself died two years before its completion, and at the time his office was the largest architecture firm in the world. The building has a Renaissance Revival design, a popular design at the time. The building was added to the National Register of Historic Places on December 18, 1978.",
    "Christ Church Limestone, also known as the Old Stone Church, began as a congregation in Norwood of English and Welsh immigrants in 1834. The church was constructed by members from local materials and in the architectural style of their homelands. Limestone for the construction was quarried from a nearby creek and the gated pews were hewn from local walnut. The cornerstone was laid on May 17, 1844 and the finished structure was consecrated on December 10, 1845. Formerly an Episcopal congregation, Christ Church Limestone is now a member of the Anglican Church, Diocese of Quincy. The building was added to the National Register of Historic Places on December 18, 1978.",
    "The Cumberland Presbyterian Church, also known as the Peoria Musicians Club, is the oldest standing church building in Peoria, Illinois. The church was constructed in 1856 as the First Cumberland Presbyterian Church. It was used by various churches and a synagogue until 1913, when it was bought by the American Federation of Musicians Local 26. The building was added to the National Register of Historic Places on March 18, 1980. It is now a branch of Busey Bank.",
    "The Judge John C. Flanagan Residence is a house in Peoria, Illinois. The home was constructed for Judge John C. Flanagan in 1837. The house was either part of an original 620 acre tract purchased by Flanagan's father from local Native American tribes or part of a 20 acre tract purchased by Flanagan when he came to Peoria in 1831. It is believed that Abraham Lincoln was once a guest in the home during the Lincoln-Douglas debates from 1854 to 1860. The building was added to the National Register of Historic Places on September 5, 1975. The house is now operated by the Peoria Historical Society as the John C. Flanagan House Museum, a 19th-century period historic house museum. The house also serves as the headquarters for the Peoria Chapter of the Daughters of the American Revolution.",
    "The Judge Jacob Gale House is located at 403 Northeast Jefferson Avenue, Peoria, Illinois. The home was constructed for Judge Jacob Gale around 1839. The Greek Revival house was built within the five years following the planning of the city's downtown and the establishment of the streets. It was added to the National Register of Historic Places on March 19, 1982.",
    "The Grand Army of the Republic Memorial Hall was constructed as a memorial to American Civil War soldiers in Peoria, Illinois in 1909. It was designed by Hewett & Emerson. The Classical Revival hall was dedicated to Joseph B. Greenhut, Captain of Company K, 82nd Illinois Volunteer Infantry Regiment. The building was added to the National Register of Historic Places on July 13, 1976.",
    "Grandview Drive is a two and a half mile scenic road with adjacent park areas through Peoria and Peoria Heights, Illinois. Major portions of the road give a view of the Illinois River and its valley as well as clear views of some of the most prestigious and historic homes in the area. Houses along Grandview Drive are among the best known in the city. The district was added to the National Register of Historic Places as an historic district in 1996. The drive was one of the first linear parks of its time. President Theodore Roosevelt is said to have proclaimed it the World's Most Beautiful Drive during a 1910 visit. Local radio station WMBD's callsign is associated with Roosevelt's comment.",
    "The Illinois Waterway Project Office is a maintenance shop and project office for the Illinois Waterway, the system of rivers and canals through Illinois which connect the Mississippi River to Lake Michigan. The complex is located at 257 Grant Street in Peoria, Illinois. The U.S. Army Corps of Engineers established the office in 1913 to house and maintain its boats. The historic district is comprised of five maintenance buildings, the 1913 harbor, marine ways, and three boats stationed in the harbor. The office was added to the National Register of Historic Places on March 10, 2004.",
    "The International Harvester Building is a five-story building in Peoria, Illinois. The property consists of the 1914 five-story building and a 1925 one-story addition. The building is associated with Peoria's history as a major shipping point due to its vicinity to the Illinois River and major railroad connections. The structure was added to the National Register of Historic Places on November 15, 2005.",
    "Jubilee College State Historic Site near Peoria, IL was a frontier Illinois college active from 1840 to 1862. Jubilee College, and the frontier community that supported it, was founded in 1839 by Episcopal bishop Philander Chase. This was one of the earliest educational enterprises in Illinois. After the Bishop's death, the college closed in 1862. In 1933 the college and grounds were presented to the state of Illinois and are still owned by the state. Though the state park is still open, the historic site was closed on November 30, 2008. The Jubilee College site was added to the National Register of Historic Places in 1972.",
    "The Kickapoo Building is a historic commercial building located at 726 West Main Street in Peoria, Illinois. Built in 1911, the building was originally used as a tied house for the Anheuser-Busch Brewery, which sought to expand its presence in Peoria's large brewing industry. The two-story building has a flatiron shape, a design which took advantage of its triangular lot. Architect Albert Keifer gave the building a Classical Revival design with German Renaissance Revival features. Flatiron buildings were once commonly built in Peoria as a necessity of the city's geography; while downtown Peoria was built on a grid aligned with the Illinois River, its subsequent additions were usually aligned with the cardinal directions, and extensions of streets from the additions into downtown led to the creation of many triangular lots. Modern commercial development and freeway construction eliminated many of Peoria's diagonal streets downtown, and took many of its flatiron buildings with it; the Kickapoo Building stands out among the survivors for its decorative commercial storefronts on all three sides. The building was added to the National Register of Historic Places on December 31, 2013.",
    "The Lincoln Branch Peoria Public Library is a Carnegie library located at 1312 West Lincoln Avenue in Peoria, Illinois. Built in 1910, the building served as the first dedicated library building on Peoria's South Side. The South Side branch library opened in 1903 in a building called the Neighborhood House; however, it had outgrown its space in the building by 1909. The city petitioned the Carnegie Foundation for funding for a new library; the Foundation provided a $20,000 grant for the building, and the city passed a $2,000 annual tax to cover the library's maintenance. Peoria architecture firm Hotchkiss & Harris supplied a Classical Revival design for the building, and construction began in 1910 and was completed the following year. The library became popular with neighborhood residents, setting city records for daily circulation; it also held special collections serving the city's Lebanese and German immigrant communities. The library was added to the National Register of Historic Places on May 28, 2014.",
    "The Madison Theatre is a historic theater in Peoria, Illinois that opened on October 16, 1920 as a silent picture theatre. The building was commissioned by Dee Robinson and designed by Frederick Klein. The theatre features an Italian Renaissance exterior and classical plasterwork on the interior walls and domed lobby ceilings. The lobby's terra-cotta plasterwork frames a triple-arched window above the marquee. The theatre closed in 2003. It was added to the National Register of Historic Places on November 21, 1980. On June 4th 2016, firefighters were called to the theater for a significant fire that had broken out around the stage area. Officials stated the fire had been deliberately set, with damages estimated to be about $500,000.",
    "The Marquette Building Apartments were designed in 1924 by Hewitt & Emerson Architects, the same group that designed the Commerce Bank Building and the Pere Marquette Hotel. This historic building is located at the intersection of Main St. and Perry Ave.It was added to the National Register of Historic Places on December 27, 2016",
    "The North Side Historic District is a Registered Historic District in Peoria, Illinois, United States. The district is located on a terrace at the bank of the Illinois River and is predominantly residential. There are 213 contributing properties listed on the registration. Among them are: the Scottish Rite Cathedral, the Peoria Diocese buildings of the former high schools Spalding Institute and Academy of Our Lady, adjacent offices and convent, and Saint Mary's Cathedral and its diocesan chancery. The district was added to the National Register of Historic Places on November 21, 1983.",
    "Peace and Harvest are two 8-foot tall limestone statues in downtown Peoria, Illinois. The male and female figures represent peace and harvest respectively. The statues were sculpted by Chicagoan Mary Andersen Clark (formerly of Peoria) as part of the Works Progress Administration's Federal Art Project. They were added to the National Register of Historic Places in 1988. The statues, created in 1938 and 1939, were dedicated on September 3, 1939 in front of the Peoria Municipal Tuberculosis Sanitarium, and stood at the site until the sanitarium closed in 1975. They then moved to Peoria Courthouse Plaza from 1975 to 1988, and then were stored in a Peoria firehouse until 1992, causing them to briefly lose their National Register status. In June 1992, the statues were placed at their current site in front of the Becker Building at the corner of Jefferson and Main Streets.",
    "The Peoria Automobile Club is the central feature of Shore Acres Park in Chillicothe, Illinois. In 1911, the Peoria Automobile Club was formed as a social and recreational organization for the automobile owners of Peoria and the surrounding cities. The club built their clubhouse in 1915 with a Classical Revival design from Peoria architects Hotchkiss & Harris. One of the club's main functions was to advocate for improved roads in Peoria and Central Illinois. They advocated for a route from Peoria to Chicago that would pass their clubhouse. The 1918 State Bond Issue, which established Illinois' state highway system, provided funding for this route, which became known as Illinois Route 29. The clubhouse was added to the National Register of Historic Places on August 4, 1995.",
    "Peoria City Hall, located in Peoria, Illinois, was designed and built by Reeves and Baillee in 1897 for $271,500. The city hall was dedicated January 5 to January 7, 1899. The building is still Peoria's city hall and was listed on the National Register of Historic Places on February 6, 1973.",
    "The Peoria Cordage Company buildings are located in an area of industrial and commercial buildings in Peoria, Illinois. Most of the buildings in the area were constructed between 1890 and 1920. The three buildings of historical significance include the Rope Mill, the New Mill and the Old Mill. The company was founded in 1888 by Edward C. Heidrich and Martin Kingman in response to the growing demand for binding twine. The site includes work by architects Hewitt & Emerson, and was listed on the National Register of Historic Places in 1982.",
    "Peoria Mineral Springs is 14,500 year old natural spring in the city of Peoria, Illinois. The site, also known as Spring Hill, is located on a hillside on the historic West Bluff. In 1843, a cave-like barrel-vaulted brick reservoir was constructed; the structure is concealed within the hillside and captures the flow of three separate springs. The brick reservoir was built for Peoria's first water company, prior to that the site was a Native American campground. Artifacts can still be found around the site. The site was added to the U.S. National Register of Historic Places on March 5, 1982.",
    "Peoria State Hospital Historic District, also known as Bartonville State Hospital or Illinois Asylum for the Incurable Insane, was a psychiatric hospital operated by the State of Illinois from 1902 to 1973. The hospital is located in Bartonville, Illinois, near Peoria, IL. The hospital grounds and its 47 buildings have been listed as a historic district on the National Register of Historic Places since 1982.",
    "The Peoria Warehouse Historic District is a historic industrial district located to the southwest of downtown Peoria, Illinois. The district includes 68 buildings, 59 of which are considered contributing to its historic status; these buildings include warehouses and other industrial structures and were built from the 1880s through the 1920s. The buildings generally have utilitarian designs inspired by the Chicago school and are built with reinforced concrete frames and brick exteriors. Peoria became a significant industrial and shipping center in the late 19th century, and development boomed in the district due to its access to the Illinois River and the city's numerous rail lines. The industries present in the district reflected the city's economy as a whole and included brewing and distillery, the manufacture of farm implements, and iron and steel production. The district was added to the National Register of Historic Places on September 17, 2014.",
    "Peoria Waterworks is a building complex built in 1890 for the Peoria, Illinois water system. The three building site was constructed in 1890 after the publicly owned Peoria Water Company was sold to John Moffat and Henry Hodgskins. The building was designed in Romanesque Revival style and first supplied water to the city of Peoria on December 1, 1890. The three structures, Pumping Station #1, Pumping Station #2 and the Main Well House, were included on the property's listing on the National Register of Historic Places on March 18, 1980.",
    "Pere Marquette, is a historic fourteen story hotel in downtown Peoria, Illinois. Built in 1926, the building is Peoria's only surviving example of an upscale 1920s hotel. Philadelphia architect Horace Trumbauer was the lead architect for the hotel. Trumbauer designed many prominent homes and public buildings on the East Coast, including several upscale hotels. The fourteen story building is mainly built from brick and stone. Its exterior design mainly emphasizes symmetry and linearity, a common architectural trend at the time. Stone window treatments surround the second-story windows, and a stone cornice with carved Native American and animal faces encircles the top of the building. It was listed on the National Register of Historic Places in 1982.",
    "The Pettengill Morron House, or Morron House, is a house located in Peoria, Illinois. The 1868 mansion was originally built for Moses Pettengill, a hardware store owner who came to Peoria from New Hampshire in 1833. When Pettengill arrived in Peoria there were 150 people, 30 log cabins and three frame houses. The original house on the site, an 1862 construction, was destroyed by fire in 1865. The current building was constructed in 1868 in the Second Empire style. The last resident was Miss Jean Morron, who lived there from 1953 until she died in 1966. The Peoria Historical Society acquired the house in 1967 and operates this house as a historic house museum. The house was listed on the U.S. National Register of Historic Places on April 2, 1976.",
    "The Pioneers is a bronze sculpture in Central Park in Elmwood, Illinois. The sculpture is one of several works by Elmwood native, Lorado Taft. Taft was a prominent Chicago-based sculptor with a national reputation for his monuments and fountains, including works designed for the 1893 Columbian Exposition. He donated The Pioneers to Elmwood under the condition that the city pay for its casting and mounting. The sculpture, which is 10 feet tall and weighs 3,500 pounds, depicts a pioneer family. The family is looking westward, symbolizing the pioneers' westward expansion, and the figures reflect the Midwestern realism of Taft's earlier works rather than the Renaissance inspired idealism of his later sculptures. The sculpture was dedicated on May 27, 1928, and a public ceremony was held for the occasion. The inscription below the statue reads: to the pioneers who bridged the streams, subdued the soil, and founded a state. The sculpture was listed on the National Register of Historic Places on May 4, 2001.",
    "The Pleasant Grove School is a historic school building located in Logan Township, Peoria County, Illinois, near the community of Eden. The one-room schoolhouse was built in 1856 to educate the children of Pleasant Grove, the name for the surrounding community at the time. The school was built on the same property as the community's church, which has since been demolished, and its cemetery. Local stonemason Joel Lobaugh built the school from locally quarried, rough coursed limestone. His design was utilitarian, with limestone window sills and lintels being the only decorative elements. The school served students until 1945, when all of Logan Township's schools consolidated into a single school in Eden. The school was added to the National Register of Historic Places on May 19, 1994.",
    "The John C. Proctor Recreation Center was constructed in Peoria, Illinois in 1913. The Classical Revival center was built per the provisions of its founder's will, John C. Proctor and designed by Hewitt & Emerson. The building is a facility operated by the Peoria Parks District. Facilities include a swimming pool, two gymnasiums, an auditorium, outdoor basketball courts, a playground, and the African American Hall of Fame Museum. The building was added to the National Register of Historic Places on September 6, 1979.",
    "The Rock Island Depot and Freight House is a two story railroad station and adjacent one story freight house from the turn of the 20th century. It was constructed in 1899 directly besides the Illinois River in Peoria, Illinois. The depot and freight house are Peoria's last remaining historic reminders of the importance of the railroad in the city's past. The depot was built by the Chicago, Rock Island and Pacific Railroad as the terminus of a major branch line that delivered significant goods and passengers to Peoria. The 1900 opening of the depot was attended by throngs of populous at its height before the depression of the 1880s, Peoria was a transportation hub, rivaled only by Chicago in the Midwest. After the end of train service, the building became known as River Station, and has been a restaurant, and afterwards a set of restaurants and bars. Currently the building is occupied by Martinis On Water Street, and The Blue Duck Barbecue Tavern. It is adjacent to the Peoria Riverfront Museum. The buildings were listed on the U.S. National Register of Historic Places in 1978.",
    "Springdale Cemetery is a historic, non-sectarian, active cemetery in Peoria, Illinois. It was chartered in 1855, received its first interment in 1857. Almost 78,000 individuals are buried at the cemetery. It contains a public mausoleum and 15 private mausoleums. The public mausoleum, which was designed by the Chicago architectural firm of Lovell & Lovell, was completed in 1929 and has been expanded twice. The property includes six and a half miles of winding driveways. The property is not fully developed, and as a result, the Cemetery can accommodate another 50,000 burials. The cemetery was listed on the U.S. National Register of Historic Places in 2004.",
    "The U.S. Post Office and Courthouse, located at 100 Northeast Monroe Street in Peoria, Illinois, is a U.S. district courthouse for the Central District of Illinois. The building was constructed in 1937 and 1938; it has a PWA Moderne design, a variant of Moderne architecture commonly used in Public Works Administration projects. Louis A. Simon, the Supervising Architect at the time, provided the plans for the building, while Howard Lovewell Cheney was the architect of record. The courthouse has a monumental granite exterior with limestone decorations. The building's interior features painted ceilings, Saint Genevieve marble walls, and patterned terrazzo floors. In addition to serving as a federal courthouse, the building also housed Peoria's main post office until 1981. The courthouse was added to the National Register of Historic Places on October 24, 2012.",
    "The Washington C. Wear House is a historic house located south of Princeville, Illinois. Washington C. Wear, a farmer from Ohio, had the house built in 1870. The house has an Italianate design which a local architectural survey regarded as one of the best examples of the style in rural Peoria County. The two story projecting front entrance includes a porch with square posts, an arched doorway and paired second-story windows, and a gabled pediment at the top. The house's windows are tall and narrow with bracketed hoods. The hip roof atop the house features wide eaves and paired brackets along the cornice. The house was added to the National Register of Historic Places on August 19, 1993.",
    "The West Bluff Historic District in Peoria, Illinois is mostly residential and is an example of the opulence once enjoyed by the upper class in the United States during the late 19th and early 20th centuries. Of particular note are two contributing structures designed by Frank Lloyd Wright: Francis W. Little House at 1505 West Moss Avenue, and the house at 1316 West Moss Avenue. The district was added to the National Register of Historic Places on December 17, 1976.",
    "The YWCA Building in Peoria, Illinois was built in 1928. It was designed by Hewitt, Emerson & Gregg. It sits at 301 Northeast Jefferson Avenue, at the north corner with Fayette Street in downtown Peoria. The Peoria chapter of the YWCA was founded in 1893. By 1928 it had run out of space in its original building; it raised $350,000 in just eight days to build this replacement. This building was dedicated on September 16, 1929. Among its features were an auditorium, swimming pool, chapel, several club rooms, and residential facilities for 86 people. Since April 2008, this building has been New Hope Apartments, supportive housing with 79 apartments. Renovation cost almost $8 million, and new apartments were created in part by building over the top of the pool and inside the space of the former two-story gymnasium. The building was listed on the National Register of Historic Places in 2007."
];

//=========================================================================================================================================
//Editing anything below this line might break your skill.  
//=========================================================================================================================================
exports.handler = function (event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

var handlers = {
    'LaunchRequest': function () {
        this.emit('GetNewPlaceIntent');
    },
    'GetNewPlaceIntent': function () {
        var factArr = HISTORIC_PLACES;
        var factIndex = Math.floor(Math.random() * factArr.length);
        var randomFact = factArr[factIndex];
        var speechOutput = GET_FACT_MESSAGE + randomFact;
        this.emit(':tellWithCard', speechOutput, SKILL_NAME, randomFact)
    },
    'AMAZON.HelpIntent': function () {
        var speechOutput = HELP_MESSAGE;
        var reprompt = HELP_REPROMPT;
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', STOP_MESSAGE);
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', STOP_MESSAGE);
    }
};